<?php

/*
 * Branding configs for your application
 */
return [
    'login' => [
        'page_title' => 'Masuk',
        'headline' => 'Masuk',
        'subheadline' => 'Masuk ke akun Anda menggunakan akun sosial  Anda di bawah ini.',
        'show_subheadline' => false,
        'email_address' => 'Alamat Email',
        'password' => 'Password',
        'remember_me' => 'Ingat Saya',
        'edit' => 'Ubah',
        'button' => 'Lanjutkan',
        'forget_password' => 'Lupa Password Anda?',
        'dont_have_an_account' => 'Belum Punya Akun?',
        'sign_up' => 'Daftar',
        'social_auth_authenticated_message' => 'Anda telah diautentikasi melalui __social_providers_list__. Silakan masuk ke jaringan di bawah ini..',
        'change_email' => 'Ubah Email',
        'couldnt_find_your_account' => 'Tidak Dapat Menemukan Akun Anda',
    ],
    'register' => [
        'page_title' => 'Daftar',
        'headline' => 'Daftar',
        'subheadline' => 'Daftar akun gratis Anda di bawah ini.',
        'show_subheadline' => false,
        'name' => 'Nama',
        'email_address' => 'Alamat Email',
        'password' => 'Password',
        'password_confirmation' => 'Konfirmasi Password',
        'already_have_an_account' => 'Sudah punya akun?',
        'sign_in' => 'Masuk',
        'button' => 'Lanjutkan',
        'email_registration_disabled' => 'Registrasi email saat ini dinonaktifkan. Harap gunakan sosial akun untuk login.',
    ],
    'verify' => [
        'page_title' => 'Verifikasi Akun Anda',
        'headline' => 'Verifikasi Alamat Email Anda',
        'subheadline' => 'Sebelum Anda dapat melanjutkan, Anda harus memverifikasi email Anda.',
        'show_subheadline' => false,
        'description' => 'Sebelum melanjutkan, harap periksa email Anda untuk tautan verifikasi. Jika Anda tidak menerima email tersebut.,',
        'new_request_link' => 'klik di sini untuk meminta request link lagi',
        'new_link_sent' => 'Link baru telah dikirim ke alamat email Anda.',
        'or' => 'Atau',
        'logout' => 'Klik disini untuk logout',
    ],
    'passwordConfirm' => [
        'page_title' => 'Konfirmasi Password Anda',
        'headline' => 'Konfirmasi Password',
        'subheadline' => 'Pastikan untuk mengonfirmasi kata sandi Anda di bawah ini',
        'show_subheadline' => false,
        'password' => 'Password',
        'button' => 'Konfirmasi Password',
    ],
    'passwordResetRequest' => [
        'page_title' => 'Minta Reset Kata Sandi',
        'headline' => 'Reset password',
        'subheadline' => 'Masukkan email Anda di bawah ini untuk mengatur ulang kata sandi Anda',
        'show_subheadline' => false,
        'email' => 'Alamat Email',
        'button' => 'Kirim tautan pengaturan ulang kata sandi',
        'or' => 'Atau',
        'return_to_login' => 'Kembali ke halaman Login',
    ],
    'passwordReset' => [
        'page_title' => 'Reset Password anda',
        'headline' => 'Reset Password',
        'subheadline' => 'Setel ulang kata sandi Anda di bawah ini',
        'show_subheadline' => false,
        'email' => 'Alamat Email',
        'password' => 'Password',
        'password_confirm' => 'Konfirmasi Password',
        'button' => 'Reset Password',
    ],
    'twoFactorChallenge' => [
        'page_title' => 'Two Factor Challenge',
        'headline_auth' => 'Authentication Code',
        'subheadline_auth' => 'Enter the authentication code provided by your authenticator application.',
        'show_subheadline_auth' => false,
        'headline_recovery' => 'Recovery Code',
        'subheadline_recovery' => 'Please confirm access to your account by entering one of your emergency recovery codes.',
        'show_subheadline_recovery' => false,
    ],

];
